version: "3.9"

services:
  web:
    image: ysaron/hsdeckhelper1:latest
    command: gunicorn deck_helper.wsgi:application --bind 0.0.0.0:8000
    container_name: app
    restart: always
    volumes:
      - static_volume:/home/deck_helper/web/static
      - media_volume:/home/deck_helper/web/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - celery
  db:
    image: postgres:14
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/deck_helper/web/static
      - media_volume:/home/deck_helper/web/media
    ports:
      - "80:80"
    depends_on:
      - web
  broker:
    image: redis:7
    container_name: broker
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    expose:
      - "6379"
    volumes:
      - broker:/data
  celery:
    image: ysaron/hsdeckhelper1:latest
    container_name: celery
    command: celery -A deck_helper worker -l info
    restart: always
    volumes:
      - media_volume:/home/deck_helper/web/media
    env_file:
      - .env.prod
    depends_on:
      - broker
  celery-beat:
    image: ysaron/hsdeckhelper1:latest
    container_name: celery-beat
    command: celery -A deck_helper beat -l info
    restart: always
    volumes:
      - media_volume:/home/deck_helper/web/media
    env_file:
      - .env.prod
    depends_on:
      - broker
volumes:
  postgres_data:
  static_volume:
  media_volume:
  broker: