version: "3.9"

services:
  web:
    build:
      context: ./deck_helper
      dockerfile: Dockerfile.prod
    command: gunicorn deck_helper.wsgi:application --bind 0.0.0.0:8000
    container_name: HS-Deck-Helper
    volumes:
      - static_volume:/home/deck_helper/web/static
      - media_volume:/home/deck_helper/web/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    container_name: Nginx
    volumes:
      - static_volume:/home/deck_helper/web/static
      - media_volume:/home/deck_helper/web/media
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: